/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    proyectos: Proyecto;
    equipo: Equipo;
    preguntas: Pregunta;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    equipo: EquipoSelect<false> | EquipoSelect<true>;
    preguntas: PreguntasSelect<false> | PreguntasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    cifras: Cifra;
    clientes: Cliente;
    textos: Texto;
    etapas: Etapa;
  };
  globalsSelect: {
    cifras: CifrasSelect<false> | CifrasSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    textos: TextosSelect<false> | TextosSelect<true>;
    etapas: EtapasSelect<false> | EtapasSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  /**
   * Para saber quién ha tocado qué.
   */
  nombre?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * Las fichas de Trabajo. El orden de esta lista es el orden en que salen en la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  /**
   * Menor primero. Es el orden en el que salen en la web.
   */
  orden: number;
  /**
   * La dirección de la ficha: /trabajo/ESTO. Si se cambia, el enlace antiguo deja de funcionar.
   */
  slug: string;
  /**
   * Marcado: la ficha se pinta como material pendiente.
   */
  placeholder?: boolean | null;
  /**
   * Sale en los destacados de la portada.
   */
  featured?: boolean | null;
  /**
   * La pieza central. Sólo una.
   */
  showpiece?: boolean | null;
  /**
   * 0 a 3: varía el tono del bloque.
   */
  tone?: number | null;
  title: string;
  /**
   * La frase de una línea que va bajo el nombre.
   */
  hardFact?: string | null;
  /**
   * El cuerpo de la ficha. Los párrafos se separan con una línea en blanco.
   */
  brief?: string | null;
  /**
   * Lo que sale bajo el título en Google. 150-160 caracteres: más y lo corta.
   */
  metaDescription?: string | null;
  /**
   * Tal como se lee: «17 de enero de 2026» / «17 January 2026». Vacío si no se sabe.
   */
  date?: string | null;
  /**
   * «2026», o «—» si no se sabe.
   */
  year?: string | null;
  /**
   * «Fabrik». Vacío si no aplica.
   */
  venue?: string | null;
  categories: ('cine' | 'marca' | 'aftermovie' | 'multicam' | 'drone' | 'photo' | 'ads')[];
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  verticalVideo?: (number | null) | Media;
  verticalPoster?: (number | null) | Media;
  gallery?:
    | {
        ruta: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Fotos y vídeos ya convertidos a su versión ligera. El máster se prepara en el Mac; aquí sólo se sube el resultado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Para quien no puede ver la imagen. No sale en pantalla.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * La rejilla de Nosotros. El orden de la lista es el de la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo".
 */
export interface Equipo {
  id: number;
  orden: number;
  slug: string;
  nombre: string;
  /**
   * En español va en la forma de los créditos: «Realización / Montaje».
   */
  role?: string | null;
  foto?: (number | null) | Media;
  /**
   * Marcado: la web avisa de que esa foto no es suya.
   */
  fotoEsEjemplo?: boolean | null;
  roleEsEjemplo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * El FAQ de la web. El orden de la lista es el de la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas".
 */
export interface Pregunta {
  id: number;
  orden: number;
  q: string;
  a: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'equipo';
        value: number | Equipo;
      } | null)
    | ({
        relationTo: 'preguntas';
        value: number | Pregunta;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  orden?: T;
  slug?: T;
  placeholder?: T;
  featured?: T;
  showpiece?: T;
  tone?: T;
  title?: T;
  hardFact?: T;
  brief?: T;
  metaDescription?: T;
  date?: T;
  year?: T;
  venue?: T;
  categories?: T;
  video?: T;
  poster?: T;
  verticalVideo?: T;
  verticalPoster?: T;
  gallery?:
    | T
    | {
        ruta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo_select".
 */
export interface EquipoSelect<T extends boolean = true> {
  orden?: T;
  slug?: T;
  nombre?: T;
  role?: T;
  foto?: T;
  fotoEsEjemplo?: T;
  roleEsEjemplo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas_select".
 */
export interface PreguntasSelect<T extends boolean = true> {
  orden?: T;
  q?: T;
  a?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * La ficha técnica de la portada y de Nosotros. El orden de la lista es el de la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cifras".
 */
export interface Cifra {
  id: number;
  items?:
    | {
        /**
         * «329», «+2.000». Vacío: esa cifra no se pinta.
         */
        valor?: string | null;
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La cinta de nombres de Trabajo. Mismo nombre en los dos idiomas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  items?:
    | {
        nombre: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La entradilla de cada página: el párrafo bajo el titular. Vacío: se ve el texto de siempre. Los titulares y los rótulos del menú no están aquí a propósito: son arrays de líneas para la animación de entrada, ver content/dictionaries/es.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos".
 */
export interface Texto {
  id: number;
  servicesIntro?: string | null;
  portfolioIntro?: string | null;
  jobsIntro?: string | null;
  contactIntro?: string | null;
  aboutIntro?: string | null;
  aboutWhereBody?: string | null;
  faqIntro?: string | null;
  droneIntro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Una foto por etapa del proceso, en Servicios. Vacía: se pinta el número en su lugar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etapas".
 */
export interface Etapa {
  id: number;
  etapa01?: (number | null) | Media;
  etapa02?: (number | null) | Media;
  etapa03?: (number | null) | Media;
  etapa04?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cifras_select".
 */
export interface CifrasSelect<T extends boolean = true> {
  items?:
    | T
    | {
        valor?: T;
        etiqueta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        nombre?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos_select".
 */
export interface TextosSelect<T extends boolean = true> {
  servicesIntro?: T;
  portfolioIntro?: T;
  jobsIntro?: T;
  contactIntro?: T;
  aboutIntro?: T;
  aboutWhereBody?: T;
  faqIntro?: T;
  droneIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etapas_select".
 */
export interface EtapasSelect<T extends boolean = true> {
  etapa01?: T;
  etapa02?: T;
  etapa03?: T;
  etapa04?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}